### ISSUE TITLE
Missing welcome message in a new channel

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/ZbayLite#11]
Description: in the lite version the user can create a new private channel and correctly receive a green success message but the welcome message in the channel itself is missing ("Congrats! you created a channel. (...)"). Additionally, in the beginning, the channel is loading (loading icon is present for a few minutes) even if there are no old messages to load as the channel has been created recently. 

Steps to recreate: create a new private channel in the lite version.

![Zrzut ekranu 2020-08-11 o 06 52 08](https://user-images.githubusercontent.com/68909168/89906465-b7764380-dbeb-11ea-8f66-f94ef7bb25e0.png)

**Comment by kingalg** [comment]
The welcome message is still missing - @NorbertBodziony could you check if in a new version something didn't mess up your fix?
The problem with "loading" icon after creating a channel is solved.

**Comment by NorbertBodziony** [comment]
I think we can close this @kingalg.
