### ISSUE TITLE
User can't change settings in a private channel

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/ZbayLite#13]
Description: Users can not change channel info on the owned channel in a light wallet.

Proof: 
Channel info has been changed and saved. Transaction ID has been checked and it ended up in a block. The block had a lower number than a block in the Zbay light so it should be included in the app. No changes in the saved channel info.

Steps to recreate:
1. create a private channel
2. go to settings
3. try to change channel info 
4. After some time (when the block with a transaction will go through) - check if the setting is changed according to point 3.

This bug is a stopper for issue #374

![Zrzut ekranu 2020-08-12 o 07 23 37](https://user-images.githubusercontent.com/68909168/90027059-641df700-dcb8-11ea-92d2-d7e098fddf94.png)
![Zrzut ekranu 2020-08-12 o 07 20 50](https://user-images.githubusercontent.com/68909168/90027064-64b68d80-dcb8-11ea-9c74-3599ffc10ee6.png)
![Zrzut ekranu 2020-08-12 o 07 20 39](https://user-images.githubusercontent.com/68909168/90027069-64b68d80-dcb8-11ea-96df-40e1fccea396.png)
![Zrzut ekranu 2020-08-12 o 07 20 27](https://user-images.githubusercontent.com/68909168/90027072-654f2400-dcb8-11ea-84ad-b0fb9fd45d81.png)

**Comment by NorbertBodziony** [comment]
This feature targets only public channels so it will not work on non published channels. Should we remove it or make it work on private channels @holmesworcester ?

**Comment by holmesworcester** [comment]
Let's remove this from backlog but keep the issue open.
