### ISSUE TITLE
Clearly describe the threat model when switching from Zcash to Tor

### ISSUE THREAD

**Issue by rex4539** [ZbayApp/ZbayLite#135]

**Comment by holmesworcester** [comment]
@rex4539 could you clarify what would count as success here? 

do you mean in the app UI itself? or on the settings screen where you can choose whether to send DMs over Tor instead of Zcash?

**Comment by rex4539** [comment]
Settings

**Comment by holmesworcester** [comment]
Okay, will address this this week.

**Comment by holmesworcester** [comment]
@rex4539 do you think this description is adequate?

https://www.zbay.app/faq.html#direct-messages

It gives the user an overview of what is happening, refers them to Tor and Zcash documentation to learn more, and notes that Zbay has not yet been audited and should not be used for activities where security is critical.

**Comment by rex4539** [comment]
The links are nice but It should also be clear in the settings (without the need to click and go into a rabbit hole) that switching from Zcash to Tor, you give up some privacy for convenience. That should be crystal clear to the user before they decide to switch.
