### ISSUE TITLE
Wrong welcome message - joining channel

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/ZbayLite#30]
When the user joins the public channel he receives a welcome message. Currently, the message says "Congrats! You created a channel. (...)". Created should be replaced with joined. 

![Zrzut ekranu 2020-08-25 o 06 24 10](https://user-images.githubusercontent.com/68909168/91180042-9af80200-e6e7-11ea-93ac-083716804a8d.png)

**Comment by NorbertBodziony** [comment]
Message removed completely. We do not have designs/text for joining channel.
