### ISSUE TITLE
Can't receive message with unknown sender

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/ZbayLite#31]
Description: no type of message that I've sent along with funds was able to reach the "unknown" tab. This tab is not appearing in the light version. The same actions (eg. send funds to a username with a memo unanimously) done from lite to heavy version create a message in the unknown in the heavy version. 

Step to recreate:
1. Send funds to a username logged in the lite version. It should be sent with a memo and unanimously.
2. Check if the "unknown" tab appears along with a message sent with the funds.

Note: funds are sent and received normally even when the message doesn't reach the user.

**Comment by holmesworcester** [comment]
Added detail to this.
