### ISSUE TITLE
Username overlaps "traffic light" buttons in top left, on Mac

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#315]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/213678/126386245-a5f45aaf-3586-427d-8eb7-fd8473a3369f.png">

question: do we have a test framework for catching regressions like this? 

is there a visual diffing tool that people have used so far? some options:

1. https://github.com/mapbox/pixelmatch 
2. https://blog.logrocket.com/automated-visual-regression-testing-with-jest/ 

We would add visual tests whenever we fix a bug like this.

**Comment by siepra** [comment]
https://github.com/ZbayApp/monorepo/pull/16

**Comment by siepra** [comment]
<img width="480" alt="Zrzut ekranu 2021-12-23 o 12 58 21" src="https://user-images.githubusercontent.com/15381135/147237621-e84263b9-d1c6-4381-bf75-e06d03cdee3a.png">
<img width="708" alt="Zrzut ekranu 2021-12-23 o 12 58 29" src="https://user-images.githubusercontent.com/15381135/147237625-d781b77e-7dea-4fd4-944a-ede3d0620a94.png">
