### ISSUE TITLE
Users can join a community they are invited to (frontend)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#320]
UPDATE - latest design: https://www.figma.com/file/MQtsSrtgnh1VPdWTXTW38x/Add-community-to-startup?node-id=7%3A2510

In https://github.com/ZbayApp/ZbayLite/issues/319 we give users a way to create a community and get an invite link they can share with others. Here we give people a way to use that link.

In our first iteration it doesn't have to be an openable/clickable link. It can just be something we paste in. We can create a new ticket for making links work.

When the user starts Zbay, they should be able to paste the "link" into a field and click a button that says "Join community". We can put this field in the "create community" screen, or we can have a link.  

This should open the username registration screen immediately. The user should already have a tor hidden service ready, and tor should already be starting up, even before they get to this screen. We should do as much initial setup as possible before the user gets to this screen. 

Once they submit a username we should connect to the registrar. We should display a message on this screen e.g. "Note: the community owner must be online for you to join. If you have trouble joining, leave the app open and wait until they come back online."  

Once the channel owner is online, if there are any issues with their username being a duplicate they should get errors etc. All other errors (like characters and length etc) should be checked on this end so that we catch it even if we aren't connected to the registrar (it should also be validated on the registrar side).

**Comment by holmesworcester** [comment]
@jgaylor hi! we need an addition to the design that would let the user paste in an invitation link on this page, in case opening the link doesn't work. Can you suggest something? https://www.figma.com/file/qwkBkjAbewMd4Ze6UW1rk3/Communities?node-id=266%3A299

**Comment by EmiM** [comment]
It is being done in one PR with creating community (because of common component and similar logic): https://github.com/ZbayApp/ZbayLite/pull/406
