### ISSUE TITLE
Make test repo to prove orbitdb syncing failure and share with orbitdb team

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#338]
Sometimes different clients are in different states and do not "heal". 

We should make a test that shows this happening, and provide it to the orbitdb folks.

**Comment by EmiM** [comment]
I made a separate branch on waggle `test/ipfs-initial-sync`, test and readme are in `src/nodeTest/README.md`

**Comment by holmesworcester** [comment]
We can't reproduce this failure anymore, so we've decided to close this and move on.
