### ISSUE TITLE
Owner can get an invite link for new community (frontend)

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#339]
In this issue we tackle the question of getting a working invite link. 

The "invite a friend" section in settings will look like this:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/213678/126419017-aca8687d-e878-4f5a-ae14-348b9fca10f6.png">

We could potentially expose the link with a "copy link" button, similar to what we did on the Zcash deposit address screen. We don't need to worry about member management in this iteration.

See #319 for links to design

**Comment by EmiM** [comment]
https://github.com/ZbayApp/ZbayLite/pull/410
