### ISSUE TITLE
Owner can create a community in nectar and someone can join it.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayLite#344]
Make creating communities possible in nectar, the headless layer. 

The tests that should pass are: 

- Quiet starts up
- User creates a community
- Community exists and that user is the admin.
- Everything is in place for someone to join, but it's not necessary that we test joining.

You don't have to be able to connect to it. It just has to exist.

See: #343 & #319

**Comment by EmiM** [comment]
https://github.com/ZbayApp/waggle/pull/97
