### ISSUE TITLE
Problem with sending funds on transparrent address

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/ZbayLite#69]
Description: On one of Mac computers that are used to test the problem with sending funds on transparrent address ocured. 
Transaction is generated hovewer balance is not changed and funds are not received. The other functions related to sending/receiving funds and messagess are working correctly on this computer. 

System: MacOs

**Comment by NorbertBodziony** [comment]
Everything works fine. This may be problem with zcash network or just transaction is filtered by miners.
