### ISSUE TITLE
Spawn websocket server on start of application.

### ISSUE THREAD

**Issue by NorbertBodziony** [ZbayApp/ZbayLite#71]

**Comment by gmale** [comment]
@NorbertBodziony is this something to be concerned about? Should it default to false?

https://github.com/ZbayApp/ZbayLite/blob/ZbayLite/src/main/websockets/server.js#L6-L11

**Comment by NorbertBodziony** [comment]
I don't think that is important for our use case. We are using websockets behind tor proxy so validating origin is kinda pointless.
